### ISSUE TITLE
Get position of matched argument

### ISSUE THREAD

**Issue by veeg** [Taywee/args#1]
I am looking to implement a command based utility, which will use a master args parser
and then delegate the remaining arguments to a sub-parser.

The project states that it will never support flag arguments sensitive to order.

My use-case is as follows:
`./prog --help`
shall display the master arg parser help.

`./prog COMMAND --help`
should show the COMMAND arg parser help.
Since it appears it will not be a goal to support positional/conditional flag arguments, 
I suggest adding an index position on the detected argument. That way, I can do the following:

```
catch (args::Help)
{
  if (command && args::position (help) > args::position (command))
    continue;
  
  ...
}
```
and thus delegate further processing to the command handler.

**Comment by Taywee** [comment]
This won't work in this way, as then flags would have to be shared between the subcommands, as would their types.  You can spoof something like subcommands with something similarly to this:

```cpp
/* Copyright © 2016 Taylor C. Richberger <taywee@gmx.com>
 * This code is released under the license described in the LICENSE file
 */

#include <iostream>
#include <args.hxx>

int main(int argc, char **argv)
{
    const std::vector<std::string> args(argv + 1, argv + argc);
    args::ArgumentParser parser("Parser with subcommands");
    parser.Prog(argv[0]);
    args::HelpFlag help(parser, "help", "Display this help menu", args::Matcher{'h', "help"});
    args::Group subcommandgroup(parser, "One of these subcommands is required:", args::Group::Validators::All);
    args::PosArg<std::string> subcommand(subcommandgroup, "SUBCOMMAND", "The subcommand, must be foo, bar, or baz");

    try
    {
        parser.ParseArgs(std::begin(args), std::begin(args) + 1);
    }
    catch (args::Help)
    {
        std::cout << parser;
        return 0;
    }
    catch (std::exception &e)
    {
        std::cerr << e.what() << std::endl;
        std::cerr << parser;
        return 1;
    }
    args::ArgumentParser subparser("Parser with subcommands");
    subparser.Prog(std::string(argv[0]) + " " + args[0]);
    args::HelpFlag subhelp(subparser, "help", "Display this help menu", args::Matcher{'h', "help"});

    if (args::get(subcommand) == "foo")
    {
        args::ArgFlag<int> foo(subparser, "FOO", "This is a 'int' foo flag", args::Matcher{'f', "foo"});

        try
        {
            subparser.ParseArgs(std::begin(args) + 1, std::end(args));
        }
        catch (args::Help)
        {
            std::cout << subparser;
            return 0;
        }
        catch (std::exception &e)
        {
            std::cerr << e.what() << std::endl;
            std::cerr << subparser;
            return 1;
        }
    } else if (args::get(subcommand) == "bar")
    {
        args::ArgFlag<std::string> foo(subparser, "FOO", "This is a 'std::string' foo flag", args::Matcher{'f', "foo"});

        try
        {
            subparser.ParseArgs(std::begin(args) + 1, std::end(args));
        }
        catch (args::Help)
        {
            std::cout << subparser;
            return 0;
        }
        catch (std::exception &e)
        {
            std::cerr << e.what() << std::endl;
            std::cerr << subparser;
            return 1;
        }
    } else if (args::get(subcommand) == "baz")
    {
        args::ArgFlag<char> foo(subparser, "FOO", "This is a 'char' foo flag", args::Matcher{'f', "foo"});

        try
        {
            subparser.ParseArgs(std::begin(args) + 1, std::end(args));
        }
        catch (args::Help)
        {
            std::cout << subparser;
            return 0;
        }
        catch (std::exception &e)
        {
            std::cerr << e.what() << std::endl;
            std::cerr << subparser;
            return 1;
        }
    } else
    {
        std::cerr << parser;
    }
    return 0;
}
```
```shell
 % /tmp/test -h
  /tmp/test {OPTIONS} [SUBCOMMAND]

    Parser with subcommands

  OPTIONS:

      -h, --help                        Display this help menu
      One of these subcommands is
      required:
        SUBCOMMAND                        The subcommand, must be foo, bar, or
                                          baz
      "--" can be used to terminate flag options and force all following
      arguments to be treated as positional options

 % /tmp/test foo -h
  /tmp/test foo {OPTIONS}

    Parser with subcommands

  OPTIONS:

      -h, --help                        Display this help menu
      -f[FOO], --foo=[FOO]              This is a 'int' foo flag

 % /tmp/test bar -h
  /tmp/test bar {OPTIONS}

    Parser with subcommands

  OPTIONS:

      -h, --help                        Display this help menu
      -f[FOO], --foo=[FOO]              This is a 'std::string' foo flag

 % /tmp/test baz -h
  /tmp/test baz {OPTIONS}

    Parser with subcommands

  OPTIONS:

      -h, --help                        Display this help menu
      -f[FOO], --foo=[FOO]              This is a 'char' foo flag

 % /tmp/test bix -h
  /tmp/test {OPTIONS} [SUBCOMMAND]

    Parser with subcommands

  OPTIONS:

      -h, --help                        Display this help menu
      One of these subcommands is
      required:
        SUBCOMMAND                        The subcommand, must be foo, bar, or
                                          baz
      "--" can be used to terminate flag options and force all following
      arguments to be treated as positional options

 % 
```

All in all, I don't see a way to support true subparsers that wouldn't be sloppy, and wouldn't cause flag contention.  If you want multiple different parsers, you'll have to use multiple different parsers.

**Comment by veeg** [comment]
I was planning on using multiple parsers. I only want one parser for the options up until the command. When I detect a command, a handler for that command will take over with the remaining command line arugments and parse it according to its own parser. Sharing a parser was never part of the issue.

However, the `args::Help` exception is thrown regardless of its position. I may have failed to see your magic in your solution above.

This is my actual code snippet for this
```
    args::ArgumentParser parser ("CLI utility to manipulate configuration files using Disir",
            os.str ());
    args::PosArg<std::string> command (parser, "COMMAND", "The PROG command to execute.");
    args::HelpFlag help (parser, "help", "Display this help menu and exit.",
                        args::Matcher{'h', "help"});
    args::Flag version (parser, "version", "show the PROG version and exit.",
                           args::Matcher{'v', "version"});
    args::Flag debug (parser, "debug", "debug messages from command-line-utility",
                           args::Matcher{'d', "debug"});

    try
    {
        parser.ParseCLI (argc, argv);
    }
    catch (args::Help)
    {
        std::cout << parser;
        return (0);
    }
    catch (args::ParseError e)
    {
        std::cerr << "ParserError: " << e.what () << std::endl;
        std::cerr << parser;
        return (1);
    }
    catch (args::ValidationError e)
    {
        std::cerr << "ValidationError: " << e.what () << std::endl;
        std::cerr << parser;
        return (1);
    }

    if (debug)
    {
        _debug = true;
    }

    if (version)
    {
        std::cout << version: " << "DUMMY.DUMMY.DUMMY"
            << "  (build " << "DUMMY" << ")" << std::endl;
        return (0);
    }

    if (!command)
    {
        std::cerr << parser;
        return (1);
    }

    // sub-parser handles remaning arguments per command basis
    handle_command(command, argc, argv);
```
So, regardless of the `--help` position, the exception is thrown. To circumvent this, I would have to plenty of logic to locate commands and strip arguments and all. With some positional logic to the order of arguments, this is quite much easier. The same is inputting the argv array to the handle_command - If i knew the index of the command, I would know also know what to send further to handle_command.

**Comment by veeg** [comment]
Hmm. I just realized that I only have to enhance my code like so for the help block:
```
    catch (args::Help)
    {
         if (command)
         {
             // continue to handle command
             handle_command (command, argc, argv);
         }
        std::cout << parser;
        return (0);
    }
```

So that solves this particular issue. I didn't sleep on this issue - that was the problem :)

**Comment by Taywee** [comment]
The magic with my comment is that the args are split using iterators, so the top parser only grabs the first item and ignores the rest, and then the rest of the iterators are passed to the "subparsers".  It is messy.  It would possibly be easier to handle the subcommand yourself, and use parsers for each of those subcommands.  It's difficult to handle it all in one parser, as the hierarchical nature only matches the first encountered flag, so even if you nested a parser inside another parser (which you rather easily could, as each ArgumentParser is a Group), you'd have to re-parse inside the command, as the first matching flag always matches on the first parse.

**Comment by Taywee** [comment]
Also note that argument types have new names as of version 4.0.0.  The [CHANGELOG](https://github.com/Taywee/args/blob/master/CHANGELOG) details most of these changes, and they are also reflected in the [API docs](https://taywee.github.io/args/) (which may require a hard refresh due to browser caching; you should see 4.0.0 or above on top).

**Comment by veeg** [comment]
I was planning on instantiating a whole new parser for each subcommand. But i cannot simply give the top parser a hardcoded number of elements - it may (grow over time) to be much more than just help, version and debug. Therefore, i'll need to figure out when the subcommand occurred and give the parser for that command all arguments trailing the position of the subcommand string. Since the parser is strictly sequential, i can deduce if a command was present or not based on the validity of the command positional argument.

**Comment by veeg** [comment]
So, actually, i will need to deduce the position of the command anyhow. I can of course do this manually, but would non the less be sweet to have the argparser handle it. But alas, I will manage.

**Comment by Taywee** [comment]
@veeg

I know it is a long time past, but this library as of version 5.0.0 has official support of subparsers, through kick-out options.  Checkout the [gitlike](https://github.com/Taywee/args/blob/master/gitlike.cxx) sample to see one such way it can be implemented (because of how kickout is implemented, you don't have to use a map.  You can actually set the same kick-out on any positional or flag argument and handle it from there). The ParseArgs method now returns an iterator that is pointing to the position after the last-parsed argument, so you can pass the rest into a subparser for a command if you wish.
