### ISSUE TITLE
Compilation fails in Visual Studio 2015 due to 'and' keyword

### ISSUE THREAD

**Issue by tdsat** [Taywee/args#10]
Compilation in Visual Studio 2015 fails due to the use of the 'and' keyword.

Possible solutions are 

1. Disabling language extensions in the compiler (/Za)
2. Adding `#include <ciso646>` in `args.hxxx`
3. Replacing every instance of `and` with `&&`

**Comment by Taywee** [comment]
Oh my god, you're right.  I can't believe I did that.  Consequence of doing C++ at home after doing Python all day at work.  I'll fix that immediately.

**Comment by Taywee** [comment]
Those ands were removed, though I can't compile using Visual Studio at the moment.  I'll have to close this for now.
