### ISSUE TITLE
pkg-config file is broken when CMAKE_INSTALL_{INCLUDE,LIB}DIR is absolute

### ISSUE THREAD

**Issue by alexshpilkin** [Taywee/args#108]
As per title: `source/packaging/pkgconfig.pc.in` has
```
prefix=@CMAKE_INSTALL_PREFIX@
includedir=${prefix}/@CMAKE_INSTALL_INCLUDEDIR@
```
and so can’t handle absolute paths in `CMAKE_INSTALL_INCLUDEDIR`; `CMakeLists.txt` has
```
string(REPLACE "/${CMAKE_LIBRARY_ARCHITECTURE}" "" CMAKE_INSTALL_LIBDIR_ARCHIND "${CMAKE_INSTALL_LIBDIR}")
# ... snip ...
install(FILES "${PKG_CONFIG_FILE_NAME}"
        DESTINATION "${CMAKE_INSTALL_LIBDIR_ARCHIND}/pkgconfig"
```
and so installs the pkg-config file in a completely unintended place when `CMAKE_INSTALL_LIBDIR` is absolute and `CMAKE_LIBRARY_ARCHITECTURE` is the empty string. (`CMAKE_CONFIG_DEST` is also set to a broken value but is not actually used anywhere.) This leads to pkg-config breakage on NixOS in particular.

See “[Concatenating paths when building pkg-config files](https://github.com/jtojnar/cmake-snips#concatenating-paths-when-building-pkg-config-files)” for a thorough discussion of the former problem and a suggested fix, or [KDE’s extra-cmake-modules](https://invent.kde.org/frameworks/extra-cmake-modules/-/blob/master/modules/ECMGeneratePkgConfigFile.cmake#L166) for a simpler approach to it.

**Comment by Taywee** [comment]
Thank you very much for the heads up.  I needed to get this lib working as a part of ExternalProject_Add, and was suspecting that something I had done was wrong here.  I borrowed a lot of this from the [nlohmann/json}(https://github.com/nlohmann/json) setup, but I don't really have a comprehensive understanding of CMake, and after spending the past week working with it, I no longer have any desire to fully understand it.  I'm probably just going to revert it to the state it was at before, at 6.3.0, and consider it good enough unless somebody else wants to spend the sanity necessary to make the CMake setup here more featureful than it is (allowing for find_package and ExternalProject_Add to work with it, that is).
