### ISSUE TITLE
cmake doesn't define args_INCLUDE_DIRS

### ISSUE THREAD

**Issue by yurivict** [Taywee/args#115]
The gccdiag project uses ```args_INCLUDE_DIRS``` [here](https://gitlab.com/andrejr/gccdiag/-/blob/master/CMakeLists.txt#L266).

However, ```args_INCLUDE_DIRS``` isn't defined after ```find_package(args REQUIRED)```.

Please consider adding the section "Using with cmake" to the README explaining how to use args.

**Comment by Taywee** [comment]
When this is installed with CMake, the correct usage for this project is the target.  You should be able to do this, I think, with `target_link_libraries($projectname taywee::args)`.

**Comment by Taywee** [comment]
You do make a good point.  CMake build instructions should be included.  I've added [an example CMakeLists.txt](https://github.com/Taywee/args/blob/b7d67237e8bdaa517d7fd6e4e84e1f6efa24f8c5/examples/CMakeLists.txt) to the examples directory and a note in the readme about this.  If you've installed cmake in the expected way (`cmake -s$argsdir -B$builddir && cmake --build $builddir && cmake --install $builddir`, with any optionally replaced `CMAKE_INSTALL_PREFIX`), then this should work as expected.
