### ISSUE TITLE
How to parse keyword-based arguments?

### ISSUE THREAD

**Issue by yurivict** [Taywee/args#116]
I need to parse arguments that have some general arguments, followed by a keyword after which there is a group of this keyword-specific arguments.

For example:
```
$ program --option tolerant create --db ./x.db --initialize --verbose 10
$ program --option non-tolerant add-category --db ./x.db --category 'main'
$ program --option non-tolerant verify --dir mydir --hierarchical
```

```create```, ```add-category``` and ```verify``` are keywords. They are followed by a group of other arguments specific for each keyword.

Some complex applications have such command line interface.

Does ```args``` support such use case?

**Comment by Taywee** [comment]
There is a `Nargs` option type, but it is for number of arguments that share a type.  Check the test case for it: https://github.com/Taywee/args/blob/b7d67237e8bdaa517d7fd6e4e84e1f6efa24f8c5/test.cxx#L676
The test code is probably the best documentation for potential use of this library.
Or the documentation for NargsValueFlag: https://taywee.github.io/args/classargs_1_1NargsValueFlag.html

I find Nargs unintuitive, and I personally don't utilize this functionality.  There are also the MapFlag types and such, but no combination between nargs and MapFlag.  You'd be better off using NargsValueFlag<std::string> and then mapping to an enum yourself.
