### ISSUE TITLE
Missing argument doesn't throw exception

### ISSUE THREAD

**Issue by ThomasKrenn** [Taywee/args#118]
Hello
shouldn't missing arguments throw an exception?

Below is a very simple test case that fails to throw an exception.

    TEST_CASE("Missing argument throw exception", "[args]")
    {
        args::ArgumentParser parser("A test program.", "More text");
        args::Positional<std::string> input(parser, "input", "Compulsory input");
        REQUIRE_THROWS_AS(parser.ParseArgs(std::vector<std::string>{}), args::ParseError);
    }

Best regards
Thomas

**Comment by Taywee** [comment]
Nope.  That variable gets initialized via default construction, and you can check whether it was present using the boolean operator, `if (input)`, as shown [here](https://github.com/Taywee/args/blob/6.4.6/README.md#argument-flags-positional-arguments-lists).

If you want a required argument, you can [mark it as such](https://github.com/Taywee/args/blob/6.4.6/test.cxx#L629).
