### ISSUE TITLE
parsing multiple flags similar to a compiler driver (i.e. -L -I -l -D)

### ISSUE THREAD

**Issue by darealshinji** [Taywee/args#120]
Is it possible to parse a flag that can be given multiple times and add the results into a vector?
What I want is give arguments to the command line in a similar way how it's done with gcc or other compilers and add their values to a vector (not caring about argument positions).

For example: `-Dfoo --something-else -Dbar --something-other -Dbaz`

For `-D` I would like to receive a `std::vector<std::string>` with the elements `{ "foo", "bar", "baz" }`

**Comment by Taywee** [comment]
Yes, using `ValueFlagList`.  See: https://github.com/Taywee/args?tab=readme-ov-file#argument-flags-positional-arguments-lists

**Comment by darealshinji** [comment]
Thanks. I have totally missed that.
