### ISSUE TITLE
Uninstalling deletes all system's headers

### ISSUE THREAD

**Issue by CoffeeLexer** [Taywee/args#123]
https://github.com/Taywee/args/blob/b7d67237e8bdaa517d7fd6e4e84e1f6efa24f8c5/Makefile#L32-L35

`make uninstall` tries to uninstall all system's headers

**Comment by Taywee** [comment]
No, it removes `args.hxx`, then only removes the specified `include` directory if it's empty (`rmdir` does not remove recursively like `rm -r` does).  Then it does the same thing for the man files.  There's no danger of it actually removing anything that it shouldn't.
