### ISSUE TITLE
What's the usage of CompletionFlag?

### ISSUE THREAD

**Issue by gakki2019** [Taywee/args#126]
Is there any detail description and sample of CompletionFlag usage?

**Comment by Taywee** [comment]
Some of it is shown in the [`test.cxx`](https://github.com/Taywee/args/blob/cc2368ca0d8a962862c96c00fe919e1480050f51/test.cxx#L1314) file, and the other part of it is in [`examples/bash_completion.sh`](https://github.com/Taywee/args/blob/master/examples/bash_completion.sh), but there should probably be a complete breakdown.  I'll illustrate here, and then put it in the readme for completeness.

First off, completion only works for Bash.  I don't know if it could be drop-in for zsh or any other shell.

Effectively, if you have this file as `completiontest.cxx`:

```cpp
#include <iostream>
#include <args.hxx>
int main(int argc, char **argv)
{
    args::ArgumentParser parser("This is a test program.", "This goes after the options.");
    args::HelpFlag help(parser, "help", "Display this help menu", {'h', "help"});
    args::CompletionFlag completion(parser, {"complete"});
    args::ValueFlag<std::string> foo(parser, "name", "description", {'f', "foo"}, "abc");
    args::ValueFlag<std::string> bar(parser, "name", "description", {'b', "bar"}, "abc");
    args::ValueFlag<std::string> baz(parser, "name", "description", {'b', "baz"}, "abc");
    try
    {
        parser.ParseCLI(argc, argv);
    }
    catch (const args::Completion& e)
    {
        std::cout << e.what();
        return 0;
    }
    catch (const args::Help&)
    {
        std::cout << parser;
        return 0;
    }
    catch (const args::ParseError& e)
    {
        std::cerr << e.what() << std::endl;
        std::cerr << parser;
        return 1;
    }
    return 0;
}
```

And you compile it to the executable `completiontest`, it will have the `--complete` flag that expects to take a completion word number, a syntax, and a list of completion words, which is how bash completion works.

Then when you run the following code in bash (usually in `.bashrc` or some other file sourced in by `.bashrc`):

```sh
_args() {
    _init_completion -n 2> /dev/null
    local program comparg

    program="${COMP_WORDS[0]}"
    comparg="--complete" # replace this with your flag

    COMPREPLY=($("$program" "$comparg" bash "$COMP_CWORD" "${COMP_WORDS[@]}" 2> /dev/null))
    [[ $COMPREPLY ]] && return
    _filedir
}
complete -F _args completiontest
```

As long as `completiontest` is in your `$PATH`, you can then type `completiontest --` and hit tab to get completions.

**Comment by Taywee** [comment]
[I've added a completion section to the readme now](https://github.com/Taywee/args?tab=readme-ov-file#completion).  Thank you for pointing out this underdocumented corner.
