### ISSUE TITLE
Allow inclusion into multiple source files

### ISSUE THREAD

**Issue by Yepoleb** [Taywee/args#15]
Currently you get a "multiple definition" error when linking two source files that include `args.hxx`. The affected functions are:

```
std::string::size_type Glyphs(const std::string &string_)
std::vector<std::string> Wrap(const std::string &in, const std::string::size_type width, std::string::size_type firstlinewidth = 0)
std::ostream &operator<<(std::ostream &os, const ArgumentParser &parser)
```

I resolved the error by making them inline or static, but I don't have much experience with header only libraries, so it may not be the best solution.

**Comment by jcjordyn130** [comment]
Last I checked making something static (in a header) duplicates it for each #include, instead of using the same instance for all #includes.

**Comment by Yepoleb** [comment]
That's how they have to behave according to the standard. It doesn't define how they are actually implemented. I highly doubt any of the modern compilers are going to duplicate the machine code.

**Comment by detche** [comment]
Subparsers reintroduce the same linker errors on MSVC (15) for the following class methods:

```c++
Command::RaiiSubparser::RaiiSubparser(ArgumentParser &parser_, std::vector<std::string> args_);
Command::RaiiSubparser::RaiiSubparser(const Command &command_, const HelpParams &params_);
void Subparser::Parse();
```

Perhaps defining them inside the class declaration would help, however definition order would have to be modifed for the Command class to be defined already, it appears. 

I moved their definition inside a cxx until this can get fixed.
