### ISSUE TITLE
Change name of the project

### ISSUE THREAD

**Issue by Yepoleb** [Taywee/args#16]
I assume you never expected this library to become so popular and just went with the most straight forward name. Unfortunately that makes it really hard to find community resources using search engines, because they see it as a generic programming keyword. Your username is really easy to recognize though, so maybe you can make that part of the project name.

However that's just a suggestion and there certainly are many arguments against a name change.

**Comment by Taywee** [comment]
I think this is a good idea, but with a name change, I would want a major API overhaul.  I'm currently working on a better, more readable API that is easier to use, and a much more restricted use case that will allow for far more descriptive messages. I'll have a rename when that is finished, but it may be a long way out (a few months, at least).  I'll close this and link to the other project when it's useable.

**Comment by travisdowns** [comment]
If you search "args.hxx" it seems to work well.

**Comment by minexew** [comment]
@Taywee has there been any progress on this new project of yours? :)

**Comment by Taywee** [comment]
@minexew Unfortunately not; I wish there had been.  It's been difficult to find time to work on it.  [There is a repo](https://github.com/Taywee/argsplus), but it never ended up in any sort of ready state.  I think, based on the direction of that one, it would be easier to just shape this into a more easily-useable state, but I don't have as much time as I used to.

To be honest, much of the useability changes that I wanted to make have already been made by @pavel-belikov in his numerous pull requests.
