### ISSUE TITLE
Q: How to setup an optional throwable version flag and other required group flags together...?

### ISSUE THREAD

**Issue by veriotis** [Taywee/args#27]
I somehow stumbled about the following here. - I wanted to have an optional -v | --version flag, just for printing out a program version, which works let's say similar like accessing the "-h | --help" output text mechanism (help exception output).  and then exits the program. 

But when I also define together a required group of value flags as to be "all" validated, a usual/normal optional flag like "-v" will never be executed, instead only always the text "Group validation failed somewhere!" output of the parser together with the help output is shown. 

See this:
```
args::ArgumentParser parser("This is a test program.", "Example: test -i file -o file");
args::HelpFlag help(parser, "help", "display this help section", {'h', "help"});
args::Flag version(parser, "version", "show the program version", {'v', "version"});

args::Group filegroup(parser, "* Required arguments: *", args::Group::Validators::All);
args::ValueFlag<std::string> input(filegroup, "file", "the input file to deal with", {'i', "input"});
args::ValueFlag<std::string> output(filegroup, "file", "the resulting output file", {'o', "output"});

try
    {
        parser.ParseCLI(argc, argv);
    }
    catch (args::Help)
    {
        std::cout << parser;
        return 0;
    }
    catch (args::ParseError e)
    {
        std::cerr << e.what() << std::endl;
        std::cerr << parser;
        return 1;
    }
    catch (args::ValidationError e)
    {
        std::cerr << e.what() << std::endl;
        std::cerr << parser;
        return 1;
    }
    if (version) { std::cout << " test v.1.0 - Copyright (c) 2017 by Testcorp" << std::endl; exit(0); }
    if (input) { inputFilename = args::get(atninput); }
    if (output) { outputFilename = args::get(atnoutput); }
    ...
    ...
```

Invoking the program with "./test -v"  or  "./test --version" gives always only

```
"Group validation failed somewhere!"
...help text...
```

So how would one handle an optional version flag setup, which behaves here like the "-h | --help" optional and allows to throw and print out just some message text and then exit, without giving out instead the parser group validation output ("Group validation failed somewhere!") together with the help text?

**Comment by Taywee** [comment]
It looks like there is no way currently to do that.  This would need a new version of the library.  I expect the easiest way to do this would be with a ThrowFlag type that accepts an exception type to be thrown on presence of its flag, and HelpFlag being redefined as a subclass of the ThrowFlag.

**Comment by veriotis** [comment]
Thank's for the clarification, in the meantime I added a VersionFlag in the manner the HelpFlag works, so optional version info can be output the same way.

```
...
args::HelpFlag help(parser, "help", "display this help section", {'h', "help"});
args::VersionFlag version(parser, "version", "show the program version", {'v', "version"});
...
try
    {
        parser.ParseCLI(argc, argv);
    }
    catch (args::Help)
    {
        std::cout << parser;
        return 0;
    }
   catch (args::Version)
    {
        std::cout << "  test v.1.0 - Copyright (c) 2017 by Testcorp" << std::endl;
        std::cout << std::endl;
        return 0;
    }
...
```

**Comment by Jin-Whu** [comment]
> Thank's for the clarification, in the meantime I added a VersionFlag in the manner the HelpFlag works, so optional version info can be output the same way.
> 
> ```
> ...
> args::HelpFlag help(parser, "help", "display this help section", {'h', "help"});
> args::VersionFlag version(parser, "version", "show the program version", {'v', "version"});
> ...
> try
>     {
>         parser.ParseCLI(argc, argv);
>     }
>     catch (args::Help)
>     {
>         std::cout << parser;
>         return 0;
>     }
>    catch (args::Version)
>     {
>         std::cout << "  test v.1.0 - Copyright (c) 2017 by Testcorp" << std::endl;
>         std::cout << std::endl;
>         return 0;
>     }
> ...
> ```

Can you supply the args.hxx? Tank you!
