### ISSUE TITLE
Prefix and postfix text in command usage string

### ISSUE THREAD

**Issue by veeg** [Taywee/args#3]
Enable the ability to add additional text before and after usage text.
Currently, my master argument parser looks like this.
```
 prog {OPTIONS} [COMMAND]
```

I would like it to look like this
```
 prog {OPTIONS} [COMMAND] [<args>]
```
even tho the `[<args>]` bit is not backed up by any args from the master parser.

When the command parser gets a `--help`, i want the usage text to say
```
prog COMMAND {OPTIONS} [X] [Y] ......
```
This requires the disabling of the auto-appended argv[0] argument, and replace it with a string of my choice.

**Comment by Taywee** [comment]
argv[0] isn't actually automatically appended if you set Prog on the ArgumentParser manually, so the prefix is unnecessary, as you can set it there.  I will look at adding this postfix text as an option, though.

**Comment by Taywee** [comment]
This is completed on tag 3.0.4

**Comment by veeg** [comment]
Ahh, lovely.

For reference, the 'prefix' can be added like this:
```
    parser.Prog("prefix string")
```

I may have failed to read the documentation thoroughly enough, but that is a a key point to bring up
in some overall documentation, just not API documentation.

**Comment by Taywee** [comment]
That's true.  Being a header library that I've thrown together for my own use, it's easy for me to overlook something that somebody else might not see; it is also very young still.
