### ISSUE TITLE
Build on VS2013 failed

### ISSUE THREAD

**Issue by ayoubserti** [Taywee/args#30]
The build on visual Studio 2013 failed due to `noexcept` keyword.

**Comment by Taywee** [comment]
This library is C++11.  I'm not going to make any attempt at supporting anything before C++11, and I don't want to put in compiler-specific preprocessor-directives.  You could possibly use a define before including the library to redefine noexcept to curb errors.

**Comment by ayoubserti** [comment]
Thank you. I will do as suggested.
