### ISSUE TITLE
A way to exclude an option from help output

### ISSUE THREAD

**Issue by travisdowns** [Taywee/args#32]
Is there any way to indicate that an option should be excluded from help output? Based on a quick scan of the code it seems like there isn't.

It is useful for "internal" flags that shouldn't be seen by the end user (for example, I have a script that launches the process with some internal flag set indicating that the process should return a value to the script, but an end-user shouldn't care about this flag).

The workaround I'm using now is to create a `Group` call `with_help`, a child of the real `ArgumentParser` and add arguments that should show help there, and internal arguments directly to the root parser, like this:

```
    args::ArgumentParser true_parser{"hidden-parser - this description won't show up anywhere"};
    args::Group with_help{parser};

    // public args
    args::HelpFlag help{with_help, "help", "Display this help menu", {'h', "help"}};
    args::Flag public_arg1{with_help, "public-arg1", "Help for arg1", {"arg1"}};
    args::Flag public_arg1{with_help, "public-arg1", "Help for arg1", {"arg1"}};

    // private args
    args::Flag public_arg1{true_parser, "hidden-arg1", "", {"hidden-arg1"}};
```
Now when I want to output I create a dummy/temporary new `ArgumentParser` and add the `with_args` child group to it:

```
    args::ArgumentParser help_parser("some-application: help goes here");
    help_parser.Add(with_help);
    std::cerr << help_parser;
```
Maybe that's already the best way?

**Comment by Taywee** [comment]
I believe there is not currently, but it should be a relatively simple feature to add.  You're right that it makes sense to be able to opt out.

**Comment by Taywee** [comment]
This was graciously fixed by @pavel-belikov.
