### ISSUE TITLE
Disallow multiple arguments for a the same value flag

### ISSUE THREAD

**Issue by ztdwu** [Taywee/args#5]
```c++
args::ValueFlag<int> integer(parser, "integer", "The integer flag", {'i'});
```
```
./program -i4 -i5
```
In this example the value at `integer` is set to 5. How can I make it an error to disallow such behaviour? I.e. only allow the `-i` flag to be passed once. Same issue with `args::Flag` too.

**Comment by Taywee** [comment]
You currently can not.  I'll add the option to have that throw an exception, as it's reasonable to want that to throw an exception.

**Comment by Taywee** [comment]
This is finished with [version 4.2.0](https://github.com/Taywee/args/tree/4.2.0).  It is an extra argument to the constructors of [args::Flag](https://taywee.github.io/args/classargs_1_1Flag.html), [args::ValueFlag](https://taywee.github.io/args/classargs_1_1ValueFlag.html), and [args::MapFlag](https://taywee.github.io/args/classargs_1_1MapFlag.html).

The error thrown is [args::ExtraError](https://taywee.github.io/args/classargs_1_1ExtraError.html), which is also a [ParseError](https://taywee.github.io/args/classargs_1_1ParseError.html).

The new constructor argument is false by default, and last in its list, so the operation of existing code that doesn't use it should be unchanged.

You can see the new test case [here](https://github.com/Taywee/args/blob/4.2.0/test.cxx#L416-L444), which demonstrates use of the new functionality.

**Comment by ztdwu** [comment]
Works as expected now. Thanks for the quick update!
