### ISSUE TITLE
Print default values in help output? 

### ISSUE THREAD

**Issue by rhd** [Taywee/args#6]
Hi, great library. I was wondering if there is a clean way to print out the default values as part of the help. 

Thanks!

**Comment by Taywee** [comment]
That's something I had also been thinking about.  I'd like that, but it does present some special challenges when the default might be of a type that can't convert to string.  It would have to be something that could be enabled/disabled on a flag-to-flag basis.

**Comment by rhd** [comment]
Yea, the 90 percent solution is to ignore things that can't be converted to a string. For my use case, it would be the 100 percent solution! 👍
