### ISSUE TITLE
Parse known args but ignore unknown ones?

### ISSUE THREAD

**Issue by zulli73** [Taywee/args#79]
Can the following be achieved by this library?

In my main() function, I want to check against "some" arguments, namely -i thefile.img, but want to ignore others, namely --gtest-xyz, as the latter will later be parsed/extraced by GoogleTest.

While GoogleTest has it's own argument parsing code, I dislike to write my own argument parser for my main() function. What I could do is adding all GoogleTest specific arguments to the parser in my main function... but that seems a bit brittle, hence I'm looking for a better solution.

I'm totally aware that this is not the standard use case for argument parser libraries... nevertheless, my hope is that this library can help me with this. Maybe I could write my own Matcher? Any hints?

**Comment by Taywee** [comment]
Wow, sorry I left this in the queue so long.  You could theoretically do it by writing your own Matcher.  You'd probably need to build your own FlagBase-derived class as well and make its `Match` method always match, but there are potentially a lot of gotchas and little corners in there.

**Comment by zulli73** [comment]
Thanks!
