### ISSUE TITLE
Memory Corruption with clang-cl

### ISSUE THREAD

**Issue by antoine-bussy** [Taywee/args#81]
Hi,

I've encountered a weird bug when using args with clang-cl on Windows, in release mode only. Using Visual Studio 2019 debugger, I suspect a memory corruption. Here is the code:

```c++
#include "args.hpp"

#include <iostream>

inline auto to_argv(std::vector<std::string>& v)
{
	auto r = std::vector<char*>{};
	for (auto& e : v)
		r.emplace_back(e.data());
	r.emplace_back(nullptr);
	return r;
}

auto other_main(int argc, char* argv[]) -> int
{
	std::cerr << argc << std::endl;
	for(auto i = 0; i < argc; ++i)
		std::cerr << argv[i] << std::endl;
	auto parser = args::ArgumentParser{ "Command Line" };
	auto const help = args::HelpFlag{ parser, "help", "Display this help menu", {'h', "help"} };
	try
	{
		parser.ParseCLI(argc, argv);
	}
	catch (const args::Help&)
	{
	}
	return 0;
}

int main(int argc, char* argv[])
{
	auto const commands = std::vector<std::string>
	{
		"command",
		"command_2",
	};
	for (auto const& command : commands)
	{
		auto _args = std::vector<std::string>
		{
			command,
			"-h",
		};
		for (auto const& a : _args)
			std::cerr << a << std::endl;
		auto args = to_argv(_args);
		other_main(static_cast<int>(args.size()) - 1, args.data());
	}
}
```

This should print:

> command
-h
2
command
-h
command_2
-h
2
command_2
-h

which it does in debug (or with MSVC or clang on Linux), but it prints:
> command
-h
2
command
-h
command_2
>  
> 2
command_2
-h

In other cases I tested, it prints rubbish, or simply crashes. I attached the whole self-contained sample, with example cmake commands.
[args_bug.zip](https://github.com/Taywee/args/files/3805331/args_bug.zip)

**Comment by Taywee** [comment]
I can't replicate the issue.  Based on the incorrect output you are reporting, that would be having issue in the `int main` loop that prints, completely separate from your use of args.  This would point to an issue in clang-cl on Windows, and not this library.  Really, everything you output doesn't touch this library at all, so I don't think this issue tracker is the correct place for this issue.  I thought it might be this library touching something that it shouldn't, but you are constructing your `_args` and `args` vector immediately before the problem output; I don't see how this library could be responsible for this.
I'd recommend either asking in the appropriate issue tracker, or possibly going to a more general-purpose C++ help channel, like ##c++-general on irc.freenode.net or something.

**Comment by antoine-bussy** [comment]
Thanks for looking into it. I agree it is probably a problem in clang-cl. For reference, I managed to simplify the sample to 40 lines, and without args :
```c++
#include <iostream>
#include <unordered_set>
#include <vector>

struct EitherFlag
{
	static auto GetLong(std::initializer_list<char>)
	{
		return std::unordered_set<std::string>{ "" };
	}
};

auto other_main()
{
	EitherFlag::GetLong({});
	try
	{
		throw 1;
	}
	catch (...)
	{
	}
}

int main(int argc, char* argv[])
{
	for (auto i = 0; i < 2; ++i)
	{
		auto args = std::vector<std::string>{ "a", "b" };
		if (args.at(1) != "b")
		{
			std::cerr << "Bug detected! (at i = " << i << ")" << std::endl;
			return 1;
		}
		other_main();
	}
	std::cerr << "Everything went fine :)" << std::endl;
	return 0;
}
```
which prints 
> Bug detected! (at i = 1)

I also opened a ticket on LLVM bugtracker:
https://bugs.llvm.org/show_bug.cgi?id=43900
