### ISSUE TITLE
Add macros to get version

### ISSUE THREAD

**Issue by gcerretani** [Taywee/args#91]
**args.hxx** is missing a macro like `ARGS_VERSION` to get the version at compile time. A triplet `ARGS_VERSION_MAJOR`, `ARGS_VERSION_MINOR` and `ARGS_VERSION_PATCH` could be even better.

It could be useful for logs, for example.

**Comment by Taywee** [comment]
Entirely reasonable, [and now added](https://github.com/Taywee/args/commit/84c7f36ee123aaea0dd6653204435e473f1b088e).
