### ISSUE TITLE
From where did you obtained catch.hpp

### ISSUE THREAD

**Issue by tillea** [Taywee/args#92]
Hi,
I'm currently busy to package args for Debian since it is a precondition for some projects of the Debian Med team.  The Debian ftpmaster has [rejected](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962193#10) the code since it is not clear how the file catch.hpp was generated.  I've searched the internet for this file but had no real luck to find the source - just other instances of that file are used in several other projects.
So could you please enlighten me where to download the real source and how the file was generated?
Kind regards, Andreas.

**Comment by pavel-belikov** [comment]
Hi

https://github.com/catchorg/Catch2/releases/tag/v2.0.1

**Comment by tillea** [comment]
Thanks a lot for the extremely quick response.
