### ISSUE TITLE
-v flag seems to trigger an args::Help exception

### ISSUE THREAD

**Issue by pettitpeon** [Taywee/args#95]
eg.:
`./myApp -v`

shows help just like 
`./myApp -h`

**Comment by Taywee** [comment]
I'd have to see the source code of the program that is causing this.  args has explicit help flag behavior, so it's likely that either you are having a parse error that you are printing help output on or you have -v set as a `args::HelpFlag`.

**Comment by pettitpeon** [comment]
Here, a treat for you ;)
The offending code
Call: `./my-tool -v` and `./my-tool -h`
```c++
#include <args.hxx> // Tag: 2.6.4, but 2.6.3 in DEFINE's
#include <iostream>

namespace
{
args::ArgumentParser s_parser("My tool");
args::HelpFlag s_version(s_parser, "version", "Display version", {'v', "version"});
args::HelpFlag s_help(s_parser, "help", "Display this help menu", {'h', "help"});
} // namespace


int main(int argc, char* argv[]) {

    try
    {
        s_parser.ParseCLI(argc, argv);
    }
    catch (const args::Help&)
    {
        // Note: Somehow '-v' triggers a help exception. This must be an args.hxx bug
        if (s_version)
        {
            std::cout << "s_version where it does not belong" << std::endl;
            return 0;
        }

        if (s_help)
        {
            std::cout << s_parser;
            return 0;
        }
    }
    catch (const std::exception& e)
    {
        std::cerr << "Error: " << e.what() << std::endl;
        std::cerr << s_parser;
        throw;
    }

    return 0;
}
```

**Comment by Taywee** [comment]
Yep, `args::HelpFlag s_version`, that's a `args::HelpFlag`.  You want a `args::Flag` instead.  `args::HelpFlag` always throws `args::Help` when matched, where a plain `args::Flag` won't, and will just let you check it for a match.

**Comment by pettitpeon** [comment]
Jesus! So sorry, my bad. You can cancel this issue

**Comment by Taywee** [comment]
No problem at all!  Happens to the best of us.
