### ISSUE TITLE
Tag 2.6.4 has PATCH = 3 in args.hxx

### ISSUE THREAD

**Issue by pettitpeon** [Taywee/args#96]
https://github.com/Taywee/args/releases/tag/6.2.4

https://github.com/Taywee/args/blob/de4db870058c37b6094bc5ccb03c9ea45708c855/args.hxx

```
#define ARGS_VERSION "6.2.3"
#define ARGS_VERSION_MAJOR 6
#define ARGS_VERSION_MINOR 2
#define ARGS_VERSION_PATCH 3
```

**Comment by Taywee** [comment]
Bumped the version defines and forced an update of that tag.  Good catch, thanks.
